-- Выполнить в Supabase SQL Editor после предыдущего setup.sql.
-- Добавляет настраиваемые статусы и приоритеты.

create table if not exists public.statuses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#667085',
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists tags_name_lower_uidx on public.tags (lower(name));

create table if not exists public.request_tags (
  request_id bigint not null references public.requests(id) on update cascade on delete cascade,
  tag_id bigint not null references public.tags(id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (request_id, tag_id)
);

create index if not exists request_tags_tag_id_idx on public.request_tags(tag_id);

alter table public.requests add column if not exists type text default 'Feature request';
alter table public.requests add column if not exists normalized_title text not null default '';
alter table public.requests add column if not exists requirement text not null default '';
alter table public.requests add column if not exists problem text not null default '';
alter table public.requests add column if not exists business_value text not null default '';
alter table public.requests add column if not exists acceptance text not null default '';
alter table public.requests add column if not exists uncertainty text not null default '';
alter table public.requests add column if not exists quality text not null default 'Не обработано';
alter table public.requests add column if not exists legacy_quality text;
alter table public.requests add column if not exists status_id bigint references public.statuses(id) on update cascade on delete set null;
alter table public.requests add column if not exists priority text not null default 'Не задан';

create index if not exists requests_status_id_idx on public.requests(status_id);
create index if not exists requests_priority_idx on public.requests(priority);

insert into public.statuses (name, color, sort_order)
values
  ('Новый', '#667085', 10),
  ('Обработать', '#7f56d9', 20),
  ('Нужно уточнить', '#f79009', 30),
  ('В YouTrack', '#2e90fa', 40),
  ('Сделано', '#12b76a', 50),
  ('Отклонено', '#f04438', 60)
on conflict (name) do update set
  color = excluded.color,
  sort_order = excluded.sort_order,
  is_active = true;

-- Переносим старое качество в новый статус только там, где status_id ещё не задан.
update public.requests r
set legacy_quality = coalesce(r.legacy_quality, r.quality),
    status_id = s.id
from public.statuses s
where r.status_id is null
  and s.name = case
    when r.quality in ('Готово', 'Можно создавать') then 'Обработать'
    when r.quality in ('Нужно уточнить', 'Недостаточно контекста', 'Требует разделения', 'Почти готово', 'Готово после уточнений', 'Уточнить', 'Не готово') then 'Нужно уточнить'
    else 'Новый'
  end;

alter table public.categories enable row level security;
alter table public.requests enable row level security;
alter table public.statuses enable row level security;
alter table public.tags enable row level security;
alter table public.request_tags enable row level security;

drop policy if exists "authenticated users can read statuses" on public.statuses;
drop policy if exists "authenticated users can insert statuses" on public.statuses;
drop policy if exists "authenticated users can update statuses" on public.statuses;
drop policy if exists "authenticated users can delete statuses" on public.statuses;

create policy "authenticated users can read statuses" on public.statuses for select to authenticated using (true);
create policy "authenticated users can insert statuses" on public.statuses for insert to authenticated with check (true);
create policy "authenticated users can update statuses" on public.statuses for update to authenticated using (true) with check (true);
create policy "authenticated users can delete statuses" on public.statuses for delete to authenticated using (true);

drop policy if exists "authenticated users can read tags" on public.tags;
drop policy if exists "authenticated users can insert tags" on public.tags;
drop policy if exists "authenticated users can update tags" on public.tags;
drop policy if exists "authenticated users can delete tags" on public.tags;
drop policy if exists "authenticated users can read request tags" on public.request_tags;
drop policy if exists "authenticated users can insert request tags" on public.request_tags;
drop policy if exists "authenticated users can update request tags" on public.request_tags;
drop policy if exists "authenticated users can delete request tags" on public.request_tags;

create policy "authenticated users can read tags" on public.tags for select to authenticated using (true);
create policy "authenticated users can insert tags" on public.tags for insert to authenticated with check (true);
create policy "authenticated users can update tags" on public.tags for update to authenticated using (true) with check (true);
create policy "authenticated users can delete tags" on public.tags for delete to authenticated using (true);
create policy "authenticated users can read request tags" on public.request_tags for select to authenticated using (true);
create policy "authenticated users can insert request tags" on public.request_tags for insert to authenticated with check (true);
create policy "authenticated users can update request tags" on public.request_tags for update to authenticated using (true) with check (true);
create policy "authenticated users can delete request tags" on public.request_tags for delete to authenticated using (true);

-- Остальные политики можно безопасно пересоздать повторно.
drop policy if exists "authenticated users can read categories" on public.categories;
drop policy if exists "authenticated users can insert categories" on public.categories;
drop policy if exists "authenticated users can update categories" on public.categories;
drop policy if exists "authenticated users can delete categories" on public.categories;
drop policy if exists "authenticated users can read requests" on public.requests;
drop policy if exists "authenticated users can insert requests" on public.requests;
drop policy if exists "authenticated users can update requests" on public.requests;
drop policy if exists "authenticated users can delete requests" on public.requests;

create policy "authenticated users can read categories" on public.categories for select to authenticated using (true);
create policy "authenticated users can insert categories" on public.categories for insert to authenticated with check (true);
create policy "authenticated users can update categories" on public.categories for update to authenticated using (true) with check (true);
create policy "authenticated users can delete categories" on public.categories for delete to authenticated using (true);
create policy "authenticated users can read requests" on public.requests for select to authenticated using (true);
create policy "authenticated users can insert requests" on public.requests for insert to authenticated with check (true);
create policy "authenticated users can update requests" on public.requests for update to authenticated using (true) with check (true);
create policy "authenticated users can delete requests" on public.requests for delete to authenticated using (true);
